language: csharp
solution: DiscordBot/DiscordBot.sln
sudo: false
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
- linux
branches:
  only:
  - master
  - dev
mono: none
dotnet: 3.1
dist: xenial
script:
- dotnet restore DiscordBot/DiscordBot.sln
- dotnet build DiscordBot/DiscordBot.sln
before_install:
- openssl aes-256-cbc -K $encrypted_f4eabd9cea96_key -iv $encrypted_f4eabd9cea96_iv
  -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy https://github.com/CheAle14/bot-binary.git
  - git push deploy
