language: csharp
solution: DiscordBot/DiscordBot.sln
mono: none
dotnet: 6.0
dist: xenial
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
    - master
    - dev

jobs:
  include:
    - name: ReleaseM
      if: branch = master
      script: 
        - dotnet publish -c LinRelease -f netcoreapp3.1 -r linux-arm DiscordBot/DiscordBot.sln
      after_success:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash deploy.sh master; fi'
      after_failure:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL
    - name: ReleaseN
      if: branch = dev
      script: 
        - dotnet publish -c LinDebug -f netcoreapp3.1 -r linux-arm DiscordBot/DiscordBot.sln -o /home/travis/build/TheGrandCoding/discord-bot/DiscordBot/bin/Release/netcoreapp3.1/linux-arm/publish/
      after_success:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash deploy.sh dev; fi'
      after_failure:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh failure $WEBHOOK_URL