language: csharp
solution: DiscordBot/DiscordBot.sln
sudo: false
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
- linux
branches:
  only:
    - master
    - dev

jobs:
  allow_failures:
    - name: Windows
  include:
    - name: ReleaseM
      if: branch = master
      script: 
        - dotnet restore DiscordBot/DiscordBot.sln
        - dotnet publish -c LinRelease -f netcoreapp3.1 -r linux-arm DiscordBot/DiscordBot.sln
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash deploy.sh; fi'
    - name: ReleaseN
      if: branch != master
      script: 
        - dotnet restore DiscordBot/DiscordBot.sln
        - dotnet publish -c LinRelease -f netcoreapp3.1 -r linux-arm DiscordBot/DiscordBot.sln
    - name: Windows
      script: 
        - dotnet restore DiscordBot/DiscordBot.sln
        - dotnet build -c WinDebug -f netcoreapp3.1 DiscordBot/DiscordBot.sln
