language: csharp
solution: DiscordBot/DiscordBot.sln
sudo: false
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
- linux
branches:
  only:
  - master
  - dev
mono: none
dotnet: 3.1
dist: xenial
script:
- dotnet restore DiscordBot/DiscordBot.sln
- dotnet publish -c LinRelease -f netcoreapp3.1 -r linux-arm DiscordBot/DiscordBot.sln
before_install:
- openssl aes-256-cbc -K $encrypted_f4eabd9cea96_key -iv $encrypted_f4eabd9cea96_iv
  -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
