language: csharp
solution: DiscordBot/DiscordBot.sln
mono: none
dotnet: 3.1

jobs:
  allow_failures:
    - name: Windows
  include:
    - name: Release
      script: 
        - dotnet restore DiscordBot/DiscordBot.sln
        - dotnet build -c LinRelease -f netcoreapp3.1 DiscordBot/DiscordBot.sln
    - name: Windows
      script: 
        - dotnet restore DiscordBot/DiscordBot.sln
        - dotnet build -c WinDebug -f netcoreapp3.1 DiscordBot/DiscordBot.sln
      