language: csharp
solution: DiscordBot/DiscordBot.sln
sudo: false
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
- linux
branches:
  only:
  - master
  - dev
mono: none
dotnet: 3.1
dist: xenial
script:
- dotnet restore DiscordBot/DiscordBot.sln
- dotnet build DiscordBot/DiscordBot.sln
before_install:
- openssl aes-256-cbc -K $encrypted_f4eabd9cea96_key -iv $encrypted_f4eabd9cea96_iv
  -in deploy_key.pem.enc -out deploy_key.pem -d
